### ISSUE TITLE
支持按人进行统计

### ISSUE THREAD

**Issue by tanghuibo** [hellodigua/code996-web#28]
一个人可以同时参与多个项目，一个项目可以同时被多个人参与，能否支持按人统计，方便揪出公司的卷王

**Comment by hellodigua** [comment]
是的，已经在写方案了，这个打算用node写，shell实现太困难了

**Comment by tanghuibo** [comment]
做成个浏览器插件怎么样？在项目也就以项目维度展示，在个人也就以个人维度进行展示。

**Comment by hellodigua** [comment]
> 做成个浏览器插件怎么样？在项目也就以项目维度展示，在个人也就以个人维度进行展示。

恐怕不行，必须依赖本地git才能拿到相关的数据

**Comment by tanghuibo** [comment]
在gitlab页面上用户已经登录过了，可以通过插件直接发起http请求获取数据，也能拿到git相关数据

**Comment by hellodigua** [comment]
> 在gitlab页面上用户已经登录过了，可以通过插件直接发起http请求获取数据，也能拿到git相关数据

这一部分是打算第三期做的，哈哈

**Comment by amazelong** [comment]
垃圾项目，脑子抽了吧，精神资本家

**Comment by popokcn** [comment]
> 揪出

哈哈，这个揪出就很传神

**Comment by wanghsinche** [comment]
> 做成个浏览器插件怎么样？在项目也就以项目维度展示，在个人也就以个人维度进行展示。

I implemented a userscript version. Give it a try. 

And I feel that the Chrome extension would be too heavy.

the PR is https://github.com/hellodigua/code996/pull/38

**Comment by hellodigua** [comment]
考虑了很久，按人统计太容易被公司利用了，所以还是不做了
