### ISSUE TITLE
PowerShell 脚本？

### ISSUE THREAD

**Issue by lc6464** [hellodigua/code996-web#31]
只支持 Shell 可不好啊，有下一步 Node 的计划也好。
现在可以先整一个 PowerShell 版本来用着，PowerShell 也支持跨平台。

**Comment by hellodigua** [comment]
不会写 PowerShell啊，如果你能支持的话就太棒了

**Comment by lc6464** [comment]
我研究研究，不保证可以写成功，如果成了给你发个 PR.

**Comment by hellodigua** [comment]
好的好的，太感谢了

**Comment by lc6464** [comment]
有不少进展，参加 lc6464/code996-fork
不过暂时有事。
