### ISSUE TITLE
[bug] timezone problem

### ISSUE THREAD

**Issue by wanghsinche** [hellodigua/code996-web#37]
git log time zone would be consolidated to UTC time in some cases, but your script doesn't deal with it, which will cause bugs in this project.

**Comment by wanghsinche** [comment]
You should use `format-local` instead of `format`

```
by_day_output=`git -C $PWD log --author=$author --date=format-local:%u --after="$time_start" --before="$time_end" |grep "Date:"|awk '{print $2}'|sort|uniq -c`

by_hour_output=`git -C $PWD log --author=$author --date=format-local:%H --after="$time_start" --before="$time_end" |grep "Date:"|awk '{print $2}'|sort|uniq -c`


```

**Comment by hellodigua** [comment]
https://github.com/hellodigua/code996/issues/17

here is same issue, can you solve this problem?
