### ISSUE TITLE
引用 cdn.bootcdn.net 资源被过广告滤规则拦截

### ISSUE THREAD

**Issue by isecret** [hellodigua/code996-web#40]
https://github.com/hellodigua/code996/blob/63c7b44c38ffec7e2e23e341c59573d7c68c013b/index.html#L12-L13

cdn.bootcdn.net 域名系供应链投毒域名之一，一些广告过滤规则已经拦截该域名，建议替换为可信源。

**Comment by hellodigua** [comment]
谢谢，已替换
